openapi: 3.0.0
info:
  title: "Comp2001 AssessmentTwo"
  description: "An API about Trails"
  version: "0.1.0"
servers:
  - url: "/api"


components:
  schemas:
    Trail:
      type: object
      properties:
        Trailid:
          type: integer
          description: "Unique identifier for the trail."
        TrailName:
          type: string
          maxLength: 128
          description: "Name of the trail."
        TrailOwnerId:
          type: integer
          description: "Identifier for the owner of the trail."
        TrailElevationgain:
          type: integer
          description: "Elevation gain of the trail in meters."
        TrailImageFileLocation:
          type: string
          maxLength: 512
          description: "File location or URL for the trail's image."
        TrailLength:
          type: number
          format: float
          description: "Length of the trail in kilometers."
        TrailRouteType:
          type: string
          maxLength: 64
          description: "Type of the trail route (e.g., loop, out-and-back)."
        TrailDescription:
          type: string
          maxLength: 512
          description: "Detailed description of the trail."
        TrailStartingPointid:
          type: integer
          description: "Identifier for the starting point of the trail."
      required:
        - TrailName
        - TrailLength
        - TrailRouteType
        - TrailDescription


paths:
  /trails:
    get:
      operationId: "TrailHandler.ReadAll"
      summary: "Get all trails"
      responses:
        '200':
          description: "A list of trails"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Trail"
    post:
      summary: "Create a new trail"
      operationId: "TrailHandler.Create"
      requestBody:
        required: true
        x-body-name: "NewTrail"
        content:
          application/json:
            schema:
              
              $ref: "#/components/schemas/Trail"
      responses:
        '201':
          description: "Trail created"
          content:
            application/json:
              schema:
                type: object
                properties:
                  Name:
                    type: string
        '400':
          description: "Invalid input"
        '406':
          description: "Trail Already Exists"
        '500':
          description: "Internal server error"

 #Fetch requests         
  /trails/{trailId}:
    get:
      operationId: "TrailHandler.ReadOne"
      summary: "Get a trail by ID"
      parameters:
        - name: "trailId"
          in: "path"
          required: true
          schema:
            type: "string"
          description: "ID of the trail to get"
      responses:
        '200':
          description: "Trail found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Trail"
        '404':
          description: "Trail not found"     


    delete:
      summary: "Delete a trail by ID"
      operationId: "TrailHandler.Delete"
      parameters:
        - name: "trailId"
          in: "path"
          required: true
          schema:
            type: "string"
          description: "ID of the trail to delete"
      responses:
        '200':
          description: "Trail deleted"
        '404':
          description: "Trail not found"
  
