openapi: 3.0.0
info:
  title: "Comp2001 AssessmentTwo"
  description: "An API about Trails"
  version: "0.1.0"
servers:
  - url: "/api"


components:
  schemas:
    Trail:
      type: object
      properties:
        Id:
          type: string
        Name:
          type: string
        Difficulty:
          type: string
        Length:
          type: number
        Location:
          type: string
      required:
        - Name
        - Difficulty
        - Length
        - Location


paths:
  /trails:
    get:
      operationId: "Trail.ReadAll"
      summary: "Get all trails"
      responses:
        '200':
          description: "A list of trails"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Trail"
