openapi: 3.0.0
info:
  title: "Comp2001 AssessmentTwo"
  description: "An API about Trails"
  version: "0.1.0"
servers:
  - url: "/api"


components:
  schemas:
    Trail:
      type: object
      properties:
        Trailid:
          type: integer
          description: "Unique identifier for the trail."
        TrailName:
          type: string
          maxLength: 128
          description: "Name of the trail."
        TrailOwnerId:
          type: integer
          description: "Identifier for the owner of the trail."
        TrailElevationgain:
          type: integer
          description: "Elevation gain of the trail in meters."
        TrailImageFileLocation:
          type: string
          maxLength: 512
          description: "File location or URL for the trail's image."
        TrailLength:
          type: number
          format: float
          description: "Length of the trail in kilometers."
        TrailRouteType:
          type: string
          maxLength: 64
          description: "Type of the trail route (e.g., loop, out-and-back)."
        TrailDescription:
          type: string
          maxLength: 512
          description: "Detailed description of the trail."
        TrailStartingPointid:
          type: integer
          description: "Identifier for the starting point of the trail."
      required:
        - TrailName
        - TrailLength
        - TrailRouteType
        - TrailDescription


paths:
  /trails:
    get:
      operationId: "TrailHandler.ReadAll"
      summary: "Get all trails"
      responses:
        '200':
          description: "A list of trails"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Trail"
